kind: pipeline
type: docker
name: build

steps:
  - name: test
    image: alpine
    commands:
      - pwd
      - ls -ashl
  - name: build
    image: node
    commands:
      - npm install
      - npm run build
  - name: test2
    image: alpine
    commands:
      - pwd
      - ls -ashl

---
kind: pipeline
type: docker
name: deploy-develop

steps:
  - name: test
    image: alpine
    commands:
      - pwd
      - ls -ashl
  - name: deploy
    image: alpine
    environment:
      FTP_HOST:
        from_secret: FTP_HOST
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
    commands:
      - which lftp || ( apk --update add lftp )
      - lftp -e "mirror -R ./dist/ dev.sp-codes.de/; bye" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST

depends_on:
  - build

trigger:
  branch:
    - develop

---
kind: pipeline
type: docker
name: deploy-master

steps:
  - name: deploy
    image: alpine
    environment:
      FTP_HOST:
        from_secret: FTP_HOST
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
    commands:
      - which lftp || ( apk --update add lftp )
      - lftp -e "mirror -R ./dist/ sp-codes.de/; bye" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST

depends_on:
  - build

trigger:
  branch:
    - master
